name: chDB-bun

on:
  pull_request:
    paths-ignore:
      - '**/.md'
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch library
      run: |
          sudo wget https://github.com/metrico/libchdb/releases/latest/download/libchdb.zip
          sudo unzip libchdb.zip
          sudo mv libchdb.so /usr/lib/libchdb.so
          sudo ldconfig
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: bun install
    - run: bun example.js
